language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=master
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.6
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_success:
  - coveralls
